feat: promote 19.1.0 (#25)
## [19.1.0]

### Added

- all
  - Added Debian12 support
- cnt
  - bl64_cnt_check_in_container,bl64_cnt_check_not_in_container: new check functions
- os
  - bl64_os_run_sleep: new wrapper function

### Changed

- core
  - Add to the auto-setup task remaining optional modules that do not require init parameters
- py
  - Optimized command detection
  - Droped obsolete globals: `BL64_PY_CMD_PYTHON3*`

### Fixed

- rxtx
  - Fixed module setup
- msg
  - bl64_msg_show_batch_finish: fixed wrong exit status when verbose=NONE

diff --git a/bin/dev-lib-testmansh b/bin/dev-lib-testmansh
--- a/bin/dev-lib-testmansh
+++ b/bin/dev-lib-testmansh
@@ -1,28 +1,61 @@
 #!/usr/bin/env bash
+#######################################
+# Dev / Lib / TestManSH / Download
 #
-# Update dev-time external tool: TestManSH
+# * Version: 4.1.0
 #
-# * Template: 4.0.0
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
 #
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
 
 #
 # Imports
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-testmansh || exit 1
+# shellcheck source-path=lib/bl64
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-api.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-vcs.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-rxtx.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Lib / TestmanSH / Source
+export DEV_LIB_TESTMANSH_REPO='https://raw.githubusercontent.com/automation64/testmansh/main/testmansh'
 
 #
 # Functions
 #
 
-function dev_lib_deploy() {
+function dev_lib_testmansh() {
   bl64_dbg_app_show_function
   bl64_msg_show_task 'download TestManSH'
   bl64_rxtx_web_get_file \
-    "$DEV_LIB_TESTMANSH_REPO" "$DEV_LIB_TESTMANSH_BIN" "$BL64_VAR_ON" '0777'
+    "$DEV_LIB_TESTMANSH_REPO" \
+    "$DEV_LIB_TESTMANSH_BIN" \
+    "$BL64_VAR_ON" \
+    '0777'
 }
 
 #
@@ -31,11 +64,7 @@ function dev_lib_deploy() {
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
 
-bl64_check_export 'DEV_LIB_TESTMANSH_BIN' &&
-  bl64_check_export 'DEV_LIB_TESTMANSH_REPO' ||
-  exit $?
-
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'lib-testmansh'
-dev_lib_deploy
-bl64_msg_show_batch_finish $? 'lib-testmansh'
+bl64_msg_show_batch_start 'dev-lib-testmansh'
+dev_lib_testmansh
+bl64_msg_show_batch_finish $? 'dev-lib-testmansh'
diff --git a/bin/dev-release-github b/bin/dev-release-github
--- a/bin/dev-release-github
+++ b/bin/dev-release-github
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 #######################################
-# Release application version
+# Dev / Release / GitHub / Create application release from tag
 #
-# * Template: 1.1.0
+# * Version: 2.1.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,15 +25,13 @@
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-git &&
+  source ./bin/dev-env-github || exit 1
 # shellcheck source=lib/bl64/bashlib64.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64.bash" || exit 1
-
-#
-# Globals
-#
-
-export DEV_PACK_STORE="${DEV_PACK_STORE:-}"
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
 
 #
 # Functions
@@ -60,7 +58,7 @@ function dev_release_get_changes() {
     print $0
     next
   }
-  ' "$DEV_CICD_REPO_CHANGELOG"
+  ' "$DEV_BASE_CHANGELOG"
 }
 
 function dev_release_create() {
@@ -69,12 +67,12 @@ function dev_release_create() {
   local notes="$2"
 
   bl64_msg_show_task "Create GitHub Release (${tag})"
-  "$DEV_LIB_GH_BIN" \
+  "$DEV_LIB_GITHUB_BIN" \
     release create \
     --latest \
     --verify-tag \
-    --repo="${DEV_CICD_RELEASE_REPO_OWNER}/${DEV_CICD_RELEASE_REPO_NAME}" \
-    --target="$DEV_CICD_BRANCH_MAIN" \
+    --repo="${DEV_RELEASE_GITHUB_REPO_OWNER}/${DEV_RELEASE_GITHUB_REPO_NAME}" \
+    --target="$DEV_GIT_BRANCH_MAIN" \
     --notes-file="$notes" \
     --title="$tag" \
     "$tag"
@@ -84,20 +82,15 @@ function dev_release_upload() {
   bl64_dbg_app_show_function "$@"
   local tag="$1"
 
-  [[ -z "$DEV_PACK_STORE" ]] && return 0
-  bl64_check_export 'DEV_PACK_NAME_SA' &&
-    bl64_check_export 'DEV_PACK_NAME_SPLIT' &&
-    bl64_check_export 'DEV_PACK_NAME_MODULAR' ||
-    return $?
+  [[ -z "$DEV_RELEASE_GITHUB_ARTIFACT" ]] && return 0
 
-  bl64_msg_show_task "Upload release assets (${DEV_PACK_STORE})" &&
-    "$DEV_LIB_GH_BIN" \
-      release upload \
-      --repo="${DEV_CICD_RELEASE_REPO_OWNER}/${DEV_CICD_RELEASE_REPO_NAME}" \
-      "$tag" \
-      "${DEV_PACK_STORE}/${DEV_PACK_NAME_SA}" \
-      "${DEV_PACK_STORE}/${DEV_PACK_NAME_SPLIT}" \
-      "${DEV_PACK_STORE}/${DEV_PACK_NAME_MODULAR}"
+  bl64_msg_show_task "Upload release assets (${DEV_RELEASE_GITHUB_ARTIFACT})"
+  # shellcheck disable=SC2086
+  "$DEV_LIB_GITHUB_BIN" \
+    release upload \
+    --repo="${DEV_RELEASE_GITHUB_REPO_OWNER}/${DEV_RELEASE_GITHUB_REPO_NAME}" \
+    "$tag" \
+    $DEV_RELEASE_GITHUB_ARTIFACT
 }
 
 function dev_release() {
@@ -119,6 +112,14 @@ function dev_release() {
   return $status
 }
 
+function dev_release_initialize() {
+  bl64_dbg_app_show_function
+  bl64_check_parameter 'dev_release_tag' &&
+    bl64_check_export 'DEV_RELEASE_GITHUB_REPO_OWNER' &&
+    bl64_check_export 'DEV_RELEASE_GITHUB_REPO_NAME' &&
+    bl64_check_command_search_path "$DEV_LIB_GITHUB_BIN"
+}
+
 #
 # Main
 #
@@ -126,15 +127,9 @@ function dev_release() {
 declare dev_release_tag="${1:-}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-bl64_check_parameter 'dev_release_tag' &&
-  bl64_check_export 'DEV_LIB_GH_BIN' &&
-  bl64_check_export 'DEV_CICD_BRANCH_MAIN' &&
-  bl64_check_export 'DEV_CICD_RELEASE_REPO_OWNER' &&
-  bl64_check_export 'DEV_CICD_RELEASE_REPO_NAME' &&
-  bl64_check_command_search_path "$DEV_LIB_GH_BIN" ||
-  exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'release'
-dev_release "$dev_release_tag"
-bl64_msg_show_batch_finish $? 'release'
+bl64_msg_show_batch_start 'dev-release-github'
+dev_release_initialize &&
+  dev_release "$dev_release_tag"
+bl64_msg_show_batch_finish $? 'dev-release-github'
diff --git a/bin/dev-test-bash b/bin/dev-test-bash
--- a/bin/dev-test-bash
+++ b/bin/dev-test-bash
@@ -1,11 +1,9 @@
 #!/usr/bin/env bash
 #######################################
-# Run test-cases
+# Dev / Test / Bash / Simple test runner
 #
-# * Test cases are done using bats-core
-# * TestManSH is used to manage test environment
-# * Tests are located in the default path "test/batscore"
-# * Template: 2.2.0
+# * Run tests in test/bash using containers
+# * Version: 1.0.0
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -24,124 +22,94 @@
 #######################################
 
 #
+# Globals
+#
+
+# Dev / Test / Base / Flag for marking container environment
+export _DEV_TEST_BASH_CONTAINER_ENVIRONMENT='OFF'
+
+#
 # Imports
 #
 
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source=lib/bl64/bashlib64-core.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-bash || exit 1
+# shellcheck source-path=lib/bl64
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-cnt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
 
 #
 # Functions
 #
 
-function dev_test_bash_ansible() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_ANSIBLE" -c "$DEV_TEST_CASE_ANSIBLE"
+function dev_test_run() {
+  bl64_dbg_app_show_function "$@"
+  local container_path="$1"
+  local test_file="$2"
+
+  bl64_msg_show_phase "run test target: ${test_file}"
+  # shellcheck disable=SC2086
+  bl64_cnt_run \
+    $BL64_CNT_SET_RM \
+    $BL64_CNT_SET_TTY \
+    --env=_DEV_TEST_BASH_CONTAINER_ENVIRONMENT='ON' \
+    --workdir="$DEV_ENV_BASH_CONTAINER_PATH_ROOT" \
+    --mount "type=bind,source=${DEV_PATH_SRC},target=${DEV_ENV_BASH_CONTAINER_PATH_SRC},readonly" \
+    --mount "type=bind,source=${DEV_PATH_ROOT},target=${DEV_ENV_BASH_CONTAINER_PATH_ROOT},readonly" \
+    --mount "type=bind,source=${DEV_PATH_TEST},target=${DEV_ENV_BASH_CONTAINER_PATH_TEST},readonly" \
+    --entrypoint="${DEV_ENV_BASH_CONTAINER_PATH_ROOT}/${test_file}" \
+    "${DEV_ENV_BASH_REGISTRY}/${container_path}" ||
+    return $?
 }
 
-function dev_test_bash_cloud() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_CLOUD" -c "$DEV_TEST_CASE_CLOUD"
-}
+function dev_test_bash() {
+  bl64_dbg_app_show_function "$@"
+  local container="$1"
+  shift
+  local target="$*"
+  local current=''
+  local tests=''
 
-function dev_test_bash_container() {
-  bl64_dbg_lib_show_function
-  local target=''
-  for target in $DEV_TEST_CONTAINER_CONTAINER; do
-    "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_CONTAINER" || exit $?
+  bl64_dbg_app_show_comments 'define target tests'
+  if [[ -z "$target" ]]; then
+    target="$DEV_TEST_BASH_CASES"
+  fi
+  if [[ -d "$target" ]]; then
+    bl64_dbg_app_show_comments "look for tests (${target})"
+    tests="$(bl64_fs_find_files "$target")" ||
+      return $?
+  else
+    tests="$target"
+  fi
+  bl64_msg_show_info "test container: ${container}"
+  for current in $tests; do
+    dev_test_run "${container}" "$current" ||
+      return $?
   done
 }
 
-function dev_test_bash_kubernetes() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_KUBERNETES" -c "$DEV_TEST_CASE_KUBERNETES"
-}
-
-function dev_test_bash_mongodb() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_MONGODB" -c "$DEV_TEST_CASE_MONGODB"
-}
-
-function dev_test_bash_non_os() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_NON_OS" -c "$DEV_TEST_CASE_NON_OS"
-}
-
-function dev_test_bash_opt() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_OPT" -c "$DEV_TEST_CASE_OPT"
-}
-
-function dev_test_bash_terraform() {
-  bl64_dbg_lib_show_function
-  "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$DEV_TEST_CONTAINER_TERRAFORM" -c "$DEV_TEST_CASE_TERRAFORM"
-}
-
-function dev_test_bash_os() {
-  bl64_dbg_lib_show_function "$@"
-  local family="$1"
-  local target=''
-  case "$family" in
-  'single')
-    for target in $DEV_TEST_CONTAINER_OS_SINGLE; do
-      "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_OS" || exit $?
-    done
-    ;;
-  'fedora')
-    for target in $DEV_TEST_CONTAINER_OS_FEDORA; do
-      "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_OS" || exit $?
-    done
-    ;;
-  'redhat')
-    for target in $DEV_TEST_CONTAINER_OS_REDHAT; do
-      "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_OS" || exit $?
-    done
-    ;;
-  'debian')
-    for target in $DEV_TEST_CONTAINER_OS_DEBIAN; do
-      "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_OS" || exit $?
-    done
-    ;;
-  'other')
-    for target in $DEV_TEST_CONTAINER_OS_OTHER; do
-      "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_OS" || exit $?
-    done
-    ;;
-  'reduced')
-    for target in $DEV_TEST_CONTAINER_OS_REDUCED; do
-      "$DEV_LIB_TESTMANSH_BIN" -b -a -e "$target" -c "$DEV_TEST_CASE_OS" || exit $?
-    done
-    ;;
-  *) bl64_check_alert_undefined "$family" ;;
-  esac
+function dev_test_initialize() {
+  bl64_dbg_app_show_function
+  bl64_cnt_setup
 }
 
 #
 # Main
 #
 
-declare dev_test_group="${1:-os}"
-declare dev_test_family="${2:-other}"
+declare dev_test_container="${1:-${DEV_TEST_BASH_CONTAINER}}"
+shift
+declare dev_test_target="${*:-}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
 
-bl64_check_export 'DEV_LIB_TESTMANSH_BIN' ||
-  exit $?
-
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'test-bash'
-case "$dev_test_group" in
-'ansible') dev_test_bash_ansible ;;
-'cloud') dev_test_bash_cloud ;;
-'container') dev_test_bash_container ;;
-'kubernetes') dev_test_bash_kubernetes ;;
-'mongodb') dev_test_bash_mongodb ;;
-'non_os') dev_test_bash_non_os ;;
-'opt') dev_test_bash_opt ;;
-'os') dev_test_bash_os "$dev_test_family" ;;
-'terraform') dev_test_bash_terraform ;;
-*) bl64_check_alert_undefined "$dev_test_group" ;;
-esac
-bl64_msg_show_batch_finish $? 'test-bash'
+bl64_msg_show_batch_start 'dev-test-bash'
+dev_test_initialize &&
+  dev_test_bash "$dev_test_container" "$dev_test_target"
+bl64_msg_show_batch_finish $? 'dev-test-bash'
