real: 13.0.0
## [13.0.0]

### Added

- api
  - new module for interacting with RESTful APIs
  - functions: bl64_api_url_encode, bl64_api_call

### Changed

- fmt
  - **Breaking change** moved bl64_fmt_strip_comments to bl64_txt_strip_comments
- txt
  - added bl64_txt_strip_comments (moved from fmt module)
- vcs
  - bl64_vcs_github_run_api: added $@ for extra params, redirect curl option. Refactored to use bl64_api_call

diff --git a/bin/dev-test-os b/bin/dev-test-os
--- a/bin/dev-test-os
+++ b/bin/dev-test-os
@@ -12,7 +12,30 @@
 source ./bin/dev-set || exit 1
 
 declare target=''
+declare family="${1:-other}"
+
 ./bin/dev-build -t || exit $?
-for target in $DEVBL_TEST_CONTAINER_OS; do
-  "$DEVBL_CICD_TESTMANSH" -b -o -e "$target" -c "$DEVBL_TEST_CASE_OS" || exit $?
-done
+
+case "$family" in
+'fedora')
+  for target in $DEVBL_TEST_CONTAINER_OS_FEDORA; do
+    "$DEVBL_CICD_TESTMANSH" -b -o -e "$target" -c "$DEVBL_TEST_CASE_OS" || exit $?
+  done
+  ;;
+'redhat')
+  for target in $DEVBL_TEST_CONTAINER_OS_REDHAT; do
+    "$DEVBL_CICD_TESTMANSH" -b -o -e "$target" -c "$DEVBL_TEST_CASE_OS" || exit $?
+  done
+  ;;
+'debian')
+  for target in $DEVBL_TEST_CONTAINER_OS_DEBIAN; do
+    "$DEVBL_CICD_TESTMANSH" -b -o -e "$target" -c "$DEVBL_TEST_CASE_OS" || exit $?
+  done
+  ;;
+'other')
+  for target in $DEVBL_TEST_CONTAINER_OS_OTHER; do
+    "$DEVBL_CICD_TESTMANSH" -b -o -e "$target" -c "$DEVBL_TEST_CASE_OS" || exit $?
+  done
+  ;;
+*) echo "invalid option" ;;
+esac
