feat: promote 17.0.0 (#13)
## [17.0.0]

### Added

- os
  - support for unknown OS version when compatibility mode is set
- py
  - support for unknown OS version when compatibility mode is set

### Changed

- pkg
  - update OS version compatibility list
- hlm
  - bl64_hlm_chart_upgrade: create namespace if missing

diff --git a/bin/dev-lib-bashlib64 b/bin/dev-lib-bashlib64
--- a/bin/dev-lib-bashlib64
+++ b/bin/dev-lib-bashlib64
@@ -5,17 +5,16 @@
 # * Use to download or install external tools, libraries, etc
 # * Tools and libs should go to lib/
 # * Do not include operations that requires privileged access (i.e. sudo)
-# * Version: v1.1.0
+# * Template: 1.2.0
 #
 
 # shellcheck source=SCRIPTDIR/dev-set
 source ./bin/dev-set || exit 1
 
+[[ -z "$DEV_CICD_BASHLIB64_REPO" ]] &&
+  echo 'error: required variable not defined (DEV_CICD_BASHLIB64_REPO)' &&
+  exit 1
+
 echo 'Download bash library: BashLib64'
 cd "$DEV_LIB" &&
-  curl -O "$DEV_CICD_BASHLIB64_REPO" || exit 1
-
-echo 'Download tools: TestManSH'
-cd "$DEV_LIB" &&
-  curl -O "$DEV_CICD_TESTMANSH_REPO" && chmod 755 testmansh ||
-  exit $?
+  curl -O "$DEV_CICD_BASHLIB64_REPO"
